{% set name = "Flask-OpenID" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 539289ed2d19af61ae38d8fe46aec9e4de2b56f9f8b46da0b98c0d387f1d975a
  skip: true  # [py<37]

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python
    - pip
    - wheel

  run:
    - python
    - flask >=0.10.1
    - python3-openid >=2.0

test:
  imports:
    - flask_openid
  requires:
    - pip
  commands:
    - pip check

about:
  home: http://github.com/mitsuhiko/flask-openid/
  license: BSD-3-Clause
  license_file: LICENSE
  license_family: BSD
  license_url: https://github.com/pallets-eco/flask-openid/blob/master/LICENSE
  summary: 'OpenID support for Flask'
  dev_url: http://github.com/mitsuhiko/flask-openid/
  doc_url: https://pythonhosted.org/Flask-OpenID/
  doc_source_url: https://github.com/pallets-eco/flask-openid/blob/master/docs/index.rst
  description: |
    Flask-OpenID is an extension to Flask that allows you to
    add OpenID based authentication to your website in a matter
    of minutes.

extra:
  recipe-maintainers:
    - pmlandwehr
    - halldc
