# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_python2.7
    - CONFIG=osx_python3.5
    - CONFIG=osx_python3.6

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "SNDE4sANjEFx3+68i1HJR7onAbY5ufs3Mk7pDc1Kjzmuk0K0oimHl3EfRtXEFNiYYGRcl42/IsM/lXOmmkG9/Ybpjx/Vvt1fCQQkF/nBCc97dnuL1oxeM2aE/qk/4WbiqA1rWA903mb3FO6BI2zlZqzcqvxjxotNAUhXJt47L50v4Fv6g6Vm/NKVyccBT/WFAmH41N/yVoj72R7k/eQEv6vz5VK5Xlt+X8n8mKTttodNLQUFidjwVQY0nSUWKpvV1H4z/9dvxgsc9SukbE/g1Fdh85sHm6qqcJcqPVcV+67SO5oPmWr0QFMIOhRyUzdWLvCuVwcpOzeRmswIkroyyfNi65pKcf3Wokbd+TRIRRZnUldiZ7AyLQM7uSaVpeBAFrenPMku7zHKLiPKTq30jilK1y9yYqjFmD90ZamqvF/gcX4yNde8dl9anKHvRWaCoN0le2FddXcdGLiXI5V1NH6nE2HCTV+/TPB0AoG7lSlgtEv88s7d6WgMr60Hma9aQY0LGRPLZdceqtrXMIPoNv79LiwZJ3NYyoHWqJedd6iOaEDAJlnCLawgo5pgnkrNUuATNDtxA8bsBVpa2flnoMEmZe6o0CqTJZu8ArC+TjHYDI9xWjrYOBmAqs61mLFHme4JEMUnIUZDhDchvAT8jJzN8uQDt3bQArHRPOgP8gQ="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
