travis:
  secure:
    BINSTAR_TOKEN: 2zlIFRizTwpH5zTL/DjDxO8e2R+E2fZjEVntpFeEgDVctl9QFd7PkC71YCl2Fm2N4ksxmJoHUn36r49EAF3Q4V/G6T/OhsqOYznCCSmGFbFg1UJ6ngQDZVxFeL1mbDiwk/zazg85JmTmR929lptc+7wbmejQ0U7x5T8R4cFqvkz2xtDrVQiGL9XFc1NpiwEj5sZJrGNccvfLSDK6eAGN6MxWaGajFIsTYt7ykZ5aBfnL55BAkEH+SzGOHXHd4gGOCfv4OPDjlRY30gyRkob6qJclcPrxVmeOCPfd0verWU0G8GsnJzEx5bSsxz51ukQxT94Ahgsh7ppnVXzGWDC0/9jUc5bQRT0WivDNy33EauH1r4JDDZ121L8SoV8p+WN1ief4dl7p2tVI1WYTTrKkohv2eX87w17rFV2TMLCFZc/mqeTNayWd9q2xovJavgmpXdKXOKE2NT8AoC8IrJtdJqNhSPxwnZRrOVEl/DJ7sMyiOnp4IHf4P7AWRCdAPDyOmBl8RbthjlEVy3FPYP8hKjdZLpRrydAptdiKWrxBw9mpoYjbjr+ztYjEmaHOafKky1rCiqSUHkei6Oyv63jJw9YQNe24u1S2a9h66KmBrhFO2fNkIMVT+Up79PUcsHzJ5pj+Zk98PAq5XqosJK6NBx6dZwtoz1E5t5pOJLuzb+I=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
