travis:
  secure:
    BINSTAR_TOKEN: UuNCvEyQCTIXAPO2fPMBewDK8Njr9j2/3ZTiadgzvF5yKZ50FTKriINUpp+t/iCr/70r0XpS/NXPTX7r6JWnz9xjaA02Q05JkBfNmsaYCQiyVmVBd9ZYPkJpgHmYVaSIOjjtPH+8xa9Jq5wtfyrBbr2uM054uwdCC2SURxP3UJjaY3W7OuZt5yLtmJtp98KRpJH8pDvqKbTz0JYeczeYXPKfoIsQnURD/IbzlBzu/Pv6Jcyw6MTa2NX8Ff8KzrCPiNsdF7NkuOmIiKabzo4HIAUjPRHSXCcvime8TRuxEie+WNwYEFB37HBxhseUGM8SXzWQzSoK812K1iTmy2O9G8yFwTlP8a3CgUFVjFpxa2q3bGwRuOJzaR1Ja3ncC39QxYNcZgKb1BEnJgr2vNsCOrF2i+HMfJJrC80EyOOYVkzQNQq7hCk8zem81XR0K6205saRfdiSlqZRc5QcpZbaao28sFFQjB3LVR2lZ30oMSamMOzt680J4KOHYQ4xbOXaykdNI9QMBRBStgvZlnALvzReKDQ2u25h1DbQlk4J3j37wY1MZXT5lOgH9lpe53mT1cgo3/F0SwxfbF+rEk5c4NvucEpGH9kUl8sZL8lXVO5DNfMb8PQQ9FsoCUqE+O+5EqehnltuRvsucVffj5nGqs1WMbXO4e/RtH2iImBSH5I=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
